
server:
  port: 8080
spring:
  application:
    name: 'loja'
  main:
    allow-circular-references: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
sample-client:
  client:
    ribbon:
      ConnectTimeout: 3000
      ReadTimeout: 3000